import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'async/sleep': 'src/async/sleep.ts',
    'notify/client': 'src/notify/client.ts',
    'auth/bearer': 'src/auth/bearer.ts',
    'auth/middleware': 'src/auth/middleware.ts',
    'http/parse-json': 'src/http/parse-json.ts',
    'http/errors': 'src/http/errors.ts',
    'hono/create-app': 'src/hono/create-app.ts',
    'r2/put': 'src/r2/put.ts',
    'r2/gold-price': 'src/r2/gold-price.ts',
    'kv/dedup': 'src/kv/dedup.ts',
    'time/shanghai': 'src/time/shanghai.ts',
    'ai/gateway': 'src/ai/gateway.ts',
    'ai/neuron-quota': 'src/ai/neuron-quota.ts',
    'ai/client': 'src/ai/client.ts',
    'secrets/resolve': 'src/secrets/resolve.ts',
    'logger/index': 'src/logger/index.ts',
    'types/env': 'src/types/env.ts',
    'id-generator/index': 'src/id-generator/index.ts',
    'email/decode-mime-header': 'src/email/decode-mime-header.ts',
    'email/regex-pattern': 'src/email/regex-pattern.ts',
    'email/probe': 'src/email/probe.ts',
    'resilience/circuit-breaker': 'src/resilience/circuit-breaker.ts',
    'email/escape-html': 'src/email/escape-html.ts',
    'env/validate': 'src/env/validate.ts',
    'ops-error/index': 'src/ops-error/index.ts',
    'fund/types': 'src/fund/types.ts',
    'fund/normalize-code': 'src/fund/normalize-code.ts',
    'fund/tencent-nav': 'src/fund/tencent-nav.ts',
    'fund/eastmoney-estimate': 'src/fund/eastmoney-estimate.ts',
    'fund/quote': 'src/fund/quote.ts',
    'monitor/threshold': 'src/monitor/threshold.ts',
  },
  format: ['esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  splitting: false,
  treeshake: true,
  external: ['hono'],
});
